catalogMode: prefer
cleanupUnusedCatalogs: true
shellEmulator: true

trustPolicy: no-downgrade
trustPolicyExclude:
  - chokidar@4.0.3
  - semver@6.3.1

packages:
  - ./
  - playgrounds/*
sharedWorkspaceLockfile: false

catalogs:
  dev:
    '@antfu/eslint-config': ^7.7.0
    '@nuxt/devtools': 3.2.3
    '@nuxt/eslint-config': ^1.15.2
    '@nuxt/module-builder': ^1.0.2
    '@nuxt/schema': ^4.3.1
    '@nuxt/test-utils': ^4.0.0
    '@types/node': ^24.12.0
    '@vitejs/plugin-legacy': ^7.2.1
    changelogen: ^0.6.2
    changelogithub: ^14.0.0
    eslint: ^10.0.3
    node-html-parser: ^7.1.0
    nuxt: ^4.3.1
    typescript: ~5.9.3
    vitest: ^4.0.18
    vue-tsc: ^3.2.5
  dev:nuxt-v3:
    # eslint-disable-next-line pnpm/yaml-no-duplicate-catalog-item
    nuxt: ^3.21.1
  dev:nuxt-v5:
    # eslint-disable-next-line pnpm/yaml-no-duplicate-catalog-item
    '@vitejs/plugin-legacy': ^8.0.0
    # eslint-disable-next-line pnpm/yaml-no-duplicate-catalog-item
    nuxt: npm:nuxt-nightly@5.0.0-29554612.0e08003b
  polyfills:
    event-target-shim: ^6.0.2
  prod:
    '@nuxt/kit': ^4.3.1

ignoredBuiltDependencies:
  - core-js
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
