catalogMode: prefer
cleanupUnusedCatalogs: true
shellEmulator: true

trustPolicy: no-downgrade
trustPolicyExclude:
  - chokidar@4.0.3
  - semver@6.3.1

packages:
  - ./
  - playgrounds/*

patchedDependencies:
  event-target-shim@6.0.2: patches/event-target-shim@6.0.2.patch

catalogs:
  dev:
    '@antfu/eslint-config': ^7.0.1
    '@nuxt/devtools': 3.1.1
    '@nuxt/eslint-config': ^1.12.1
    '@nuxt/module-builder': ^1.0.2
    '@nuxt/schema': ^4.2.2
    '@nuxt/test-utils': ^3.23.0
    '@types/node': ^24.10.9
    '@vitejs/plugin-legacy': ^7.2.1
    changelogen: ^0.6.2
    changelogithub: ^14.0.0
    eslint: ^9.39.2
    node-html-parser: ^7.0.2
    nuxt: ^4.2.2
    typescript: ~5.9.3
    vitest: ^4.0.17
    vue-tsc: ^3.2.2
  dev:nuxt-v3:
    # eslint-disable-next-line pnpm/yaml-no-duplicate-catalog-item
    nuxt: ^3.20.2
  polyfills:
    event-target-shim: ^6.0.2
  prod:
    '@nuxt/kit': ^4.2.2

ignoredBuiltDependencies:
  - core-js
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
