ignoredBuiltDependencies:
  - core-js
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
packages:
  - ./
  - playgrounds/*
catalog:
  '@antfu/eslint-config': ^6.4.2
  '@nuxt/devtools': 3.1.1
  '@nuxt/eslint-config': ^1.11.0
  '@nuxt/kit': ^4.2.1
  '@nuxt/module-builder': ^1.0.2
  '@nuxt/schema': ^4.2.1
  '@nuxt/test-utils': ^3.21.0
  '@types/node': ^24.10.1
  '@vitejs/plugin-legacy': ^7.2.1
  browserslist: ^4.28.1
  changelogen: ^0.6.2
  changelogithub: ^14.0.0
  eslint: ^9.39.1
  node-html-parser: ^7.0.1
  nuxt: ^4.2.1
  typescript: ~5.9.3
  vitest: ^4.0.15
  vue-tsc: ^3.1.6
