import type { LegacySnippets } from './runtime/snippets/index'
import type { CustomPolyfillsOptions } from './setup/custom'
import type { ViteLegacyOptions } from './setup/vite'
import { addServerTemplate, createResolver, defineNuxtModule } from '@nuxt/kit'
import { selectSnippets } from './runtime/snippets/index'
import { setupCustomPolyfills } from './setup/custom'
import { setupVite } from './setup/vite'

export { cspHashesFor } from './csp'

export interface ModuleOptions {
  vite?: ViteLegacyOptions
  customPolyfills?: CustomPolyfillsOptions
  /**
   * The package name to resolve for `@vitejs/plugin-legacy`. Used by tests to
   * redirect resolution to an aliased install (e.g. `plugin-legacy-v8`).
   *
   * @internal
   */
  viteLegacyPackageName?: string
}

export default defineNuxtModule<ModuleOptions>({
  meta: {
    name: '@teages/nuxt-legacy',
    configKey: 'legacy',
    compatibility: { nuxt: '^3.18.0 || >=4.0.3' },
  },
  defaults: {},
  async setup(options, nuxt) {
    const moduleResolver = createResolver(import.meta.url)

    // Detect the plugin-legacy version early so the snippets injected into the
    // server plugin match the installed major. Defaults to v7 when plugin-legacy
    // is absent (e.g. SSR-only or customPolyfills-only usage).
    let snippets: LegacySnippets = selectSnippets(0)
    if (options.vite && nuxt.options.builder === '@nuxt/vite-builder') {
      snippets = await setupVite(options.vite, nuxt, moduleResolver, options.viteLegacyPackageName)
    }
    await setupCustomPolyfills(nuxt, options.customPolyfills ?? {})

    // Emit the selected snippets as a virtual nitro module. The server plugin
    // imports `#nuxt-legacy/snippets` and reads the version-correct inline
    // scripts from it. We emit real source (with the `['import','meta','url'].join('.')`
    // trick) rather than `JSON.stringify`-ing the strings, because nitro's
    // bundler rewrites the literal `import.meta.url` even inside string values.
    addServerTemplate({
      filename: '#nuxt-legacy/snippets.mjs',
      getContents: () => snippetsToSource(snippets),
    })

    addServerTemplate({
      filename: '#nuxt-legacy/options.mjs',
      getContents: () => `export const options = ${JSON.stringify(options)}`,
    })
  },
})

/**
 * Renders a `LegacySnippets` set as ES module source.
 *
 * `import.meta.url` is emitted as `${['import','meta','url'].join('.')}` (live
 * code), matching the upstream plugin-legacy source, so nitro's bundler does
 * not rewrite it inside a string literal — which would break the injected
 * `detectModernBrowser` script at runtime.
 */
function snippetsToSource(snippets: LegacySnippets): string {
  // The detector uses `import.meta.url`; rebuild the join trick so it stays
  // as live code rather than a literal string.
  // eslint-disable-next-line no-template-curly-in-string
  const joinTrick = '${[\'import\', \'meta\', \'url\'].join(\'.\')}'
  const detectorWithJoinTrick = snippets.detectModernBrowserDetector.replace(
    'import.meta.url',
    joinTrick,
  )
  return [
    `// Generated by @teages/nuxt-legacy — do not edit.`,
    `const detectModernBrowserVarName = '__vite_is_modern_browser';`,
    `const detectModernBrowserDetector = \`${detectorWithJoinTrick}\`;`,
    `export const safari10NoModuleFix = ${JSON.stringify(snippets.safari10NoModuleFix)};`,
    `export const legacyPolyfillId = ${JSON.stringify(snippets.legacyPolyfillId)};`,
    `export const legacyEntryId = ${JSON.stringify(snippets.legacyEntryId)};`,
    `export const systemJSInlineCode = ${JSON.stringify(snippets.systemJSInlineCode)};`,
    `export const detectModernBrowserCode = \`\${detectModernBrowserDetector};window.\${detectModernBrowserVarName}=true\`;`,
    `export const dynamicFallbackInlineCode = ${JSON.stringify(snippets.dynamicFallbackInlineCode)};`,
  ].join('\n')
}
